language: php
php:
- '7.0'
notifications:
  email:
    on_failure: change
    on_success: change
addons:
  ssh_known_hosts:
  - 159.89.250.133
branches:
  only:
  - master
env:
  global:
  - REMOTE_APP_DIR=~
  - REMOTE_USER=deploy
  - REMOTE_HOST=159.89.250.133
  - PORT=8080
before_script:
- chmod 600 deploy && mv deploy ~/.ssh/id_rsa
script: phpunit --coverage-text tests/*
before_install:
- openssl aes-256-cbc -K $encrypted_c9ee5b34b6c3_key -iv $encrypted_c9ee5b34b6c3_iv
  -in deploy.enc -out deploy -d
deploy:
  provider: script
  skip_cleanup: true
  script: "./scripts/deploy.sh"
